### ISSUE TITLE
Waves DEX

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#1067]
Аббревиатура DEX означает [Decentralized EXchange](https://en.m.wikipedia.org/wiki/Decentralized_exchange).
Однако сайт https://client.wavesplatform.com/ централизирован,
также как централизирован и [Waves Lite Client](https://github.com/wavesplatform/WavesGUI/releases/download/v0.5.18/waves-lite-client-mainnet-v0.5.18.zip)
Там отправляются XHR-запросы на доменное имя централизованного сервиса,
который может гокснуться, как [Mt.Gox](https://ru.m.wikipedia.org/wiki/Mt.Gox).

Вопрос:
Могу ли я сделать ноду, чтобы децентрализировать DEX, и хостить её узел на DDNS?
Как например ноды на бирже [CRYPTOBRIDGE](https://wallet.crypto-bridge.org/)

_________
И ещё, если вас не затруднит - исправьте описание здесь:
1. https://client.wavesplatform.com
2. Вход.
3. Портфель.
4. Любой токен - кнопка "Отправить" - массовая отправка
5. Textarea placeholder. Там не видно новую строку в Mozilla.

Вот вам некое подобие многострочного плейсхолдера, в виде div, после textarea.
https://jsfiddle.net/01taylop/L5b4omm8/

**Comment by GIvanovWaves** [comment]
Добрый день.
Совершенно верно, вы можете запустить свою собственную ноду и указать её в настройках клиента.
Подробную информацию об установке можете посмотреть [здесь](https://docs.wavesplatform.com/en/waves-full-node/what-is-a-full-node.html)
Также, в настройкках ноды вы можете включить функцию "[матчера (DEX)](https://docs.wavesplatform.com/en/waves-full-node/configuration-parameters.html#section-7c6111e1f4b8208643d6238f3e948e29)" и указать его в настройках клиента.
Так как до момента матчинга ордера ваши средства не покидают ваш аккаунт, то в случае отключения матчера (DEX) по умолчанию, вы полностью сохраняете доступ к своим средствам.
Больше информации [здесь](https://docs.wavesplatform.com/en/development-and-api/dex-api/matcher.html)

По вопросу с Mozilla Firefox, уточните, пожалуйста, проблему.
В Firefox версии 64.0 placeholder textarea в Mass Send отображается мультистрочно.

**Comment by username1565** [comment]
@GIvanovWaves, отлично! Значит ли это, что waves - open source?
Или байт-код в JAR-файле - проприетарный?

Что касается плейсхолдера, у меня Mozilla 52.9.0 (32-бит), и всё в одну строку отображается.
Вот тут я нашёл пример с неразрывным пробелом `&nbsp;` :
https://stackoverflow.com/a/30801020/8921172
И если заполнить такими пробелами каждую строку, в зависимости от размера textarea
можно увидеть многострочный placeholder: http://jsfiddle.net/j5kcnwzr/
Но текст съезжает, если изменить её размер...

Подумалось мне, после этого, использовать многострочную всплывающую подсказку, как здесь: http://jsfiddle.net/4jugypzr/

Но... [Тут](https://stackoverflow.com/a/35669887/8921172), я нашёл мультибраузерную функцию Placeholder на чистом JS, которая сохраняет многострочный плейсхолдер, даже при изменении размера textarea. Выглядит этот так: http://jsfiddle.net/j5kcnwzr/1/
ну, или так, в виде одной страницы с JS и CSS: http://jsfiddle.net/j5kcnwzr/3/

**Comment by ravibhojwani** [comment]
Can GitHub allow translation- I will have to view using a translation layer .. no matter ..

**Comment by username1565** [comment]
@ravibhojwani, https://translate.google.com/translate?sl=ru&tl=en&u=https://github.com/wavesplatform/WavesGUI/issues/1067

**Comment by username1565** [comment]
Просьба, если есть время, сделать переключение в один клик
тикеров по торговой паре - с прямой на обратную,
внутри биржи https://client.wavesplatform.com/
и внутри биржи в [waves-lite-client-mainnet-v0.5.18.zip](https://github.com/wavesplatform/WavesGUI/releases), а также отображение реверсных цен и графики.

Например, торговая пара [LTC/ETH](https://client.wavesplatform.com/#!/dex-demo?assetId2=HZk1mbfuJpmxU1Fs4AX5MWLVYtctsNcg6e2C6VKqK8zk&assetId1=474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu) и [ETH/LTC](https://www.cryptopia.co.nz/Exchange/?market=ETH_LTC) обратны, и цены в них обратны.
Не очень удобно пересчитывать всё.

Вот, как на [Cryptobrigde.org](https://wallet.crypto-bridge.org/market/BRIDGE.BTC_BRIDGE.XMR)
там рядом с тикерами, есть кнопка со стрелочками крест накрест.

**Comment by username1565** [comment]
Чё-то не пойму как на форуме постить, и в дискорд не пускает.
У меня вопрос есть. Вот если я запускаю ноду в виде JAR-файла, на Windows,
там происходит закачка блокчейна.
Куда сохраняются блоки?
Могу ли я задать папку каким-то параметром, например, как у альткоинов,
параметром -datadir=data создав папку data рядом с jar-файлом?

**Comment by GIvanovWaves** [comment]
В параметре `data-directory` указывается путь сохранения блоков.

Русскоязычное сообщество можно найти в Telegram: https://t.me/WavesCommunityRU
К сожалению тема обсуждения вышла за рамки проблемы, вынжден закрыть.

**Comment by username1565** [comment]
Здравствуйте, @GIvanovWaves!
Вы писали:
>На данный момент, работу с USD и EURO поддерживает gateway провайдер Coinomat, больше информации [тут](https://docs.wavesplatform.com/en/waves-client/wallet-management.html).

Что у них там произошло с WUSD и WEUR? Почему они недооценены на рынке?
Это скам и они сливают премайн что-ли?
