### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [wavesplatform/WavesGUI#1072]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support WAVES on our service for a long time and we have been exchanging WAVES for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by username1565** [comment]
To @SimpleSwap:
____
Hello, Nicolas!
[Here](https://client.wavesplatform.com/) and [here](http://waveswallet.io/) ([portable zip version](https://github.com/wavesplatform/WavesGUI/releases))
is already possible to deposit/exchange/withdraw BTC, LTC, ETH, ZCash, etc..
Instantly on the generated address.

But if you want to receive Waves and tokens to your wallet,
you can using the invoices, [like this](https://client.wavesplatform.com/#send/8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS?recipient=3PHwTZasBNSnDJNP68v7Awcs3paRLTHnoao&amount=50.00000000)
and wait the transactions, by parsing JSON-response,
from the waves node, where the transaction will be confirmed.
[As you can see here](https://documenter.getpostman.com/view/2733299/waves-full-node/RVnWiKZJ) to check the transaction, can be used the GET-query
`https://127.0.0.1:6869/transactions/address/:address/limit/:limit`,
where `127.0.0.1:6869` IP:port or domain name for the node,
`:address` - your address, `:limit` - the number of transactions to return.
In the result JSON response,
the value `totalAmount` means the number of minimum units of received token.

Have a nice day.

**Comment by GIvanovWaves** [comment]
@SimpleSwap 
I am very sorry for the late answer.
You should contact Vadim Radskiy radskiy@wavesplatform.com
