### ISSUE TITLE
 waves-lite-client not working without connection to nodes.wavesnodes.com

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#1076]
[waves-lite-client-mainnet-v0.5.18.zip](https://github.com/wavesplatform/WavesGUI/releases)
not working without connection to nodes.wavesnodes.com.
There is an errors:

```
GET https://nodes.wavesnodes.com/blocks/height net::ERR_CONNECTION_TIMED_OUT waves-lite-client-mainnet-0.5.18.js:23542
GET https://nodes.wavesnodes.com/transactions/unconfirmed net::ERR_CONNECTION_TIMED_OUT waves-lite-client-mainnet-0.5.18.js:23542
```
Do you have any another server or domain name for this service?

**Comment by ravibhojwani** [comment]
The lite client has been upgraded I think .. use the desktop ?

**Comment by username1565** [comment]
@ravibhojwani no, not desktop client,
just waves-lite-client worked good for me, in browser, but today I see this.
I cann't open the site https://nodes.wavesnodes.com/
and maybe for that reason, the volumes of trading - go down.

P.S.: I see here https://nodes.wavesplatform.com/api-docs/index.html
is available Waves Full Node API,
and links [blockchain height](https://nodes.wavesplatform.com/blocks/height) and [unconfirmed transactions](https://nodes.wavesplatform.com/transactions/unconfirmed) working on the site https://nodes.wavesplatform.com

So I just did changes in waves-lite-client-mainnet-0.5.18.js at line 118353:
`javascript
            //NODE_ADDRESS: 'https://nodes.wavesnodes.com',
            NODE_ADDRESS: 'https://nodes.wavesplatform.com',
`
and waves-lite-client now working for me.

This issue is closed, but anyone can post here more links, like
https://nodes.wavesnodes.com/blocks/height
https://nodes.wavesplatform.com/blocks/height
etc...
