### ISSUE TITLE
Customising the Waves Client

### ISSUE THREAD

**Issue by layinka** [wavesplatform/WavesGUI#1077]
Hi,

Please can someone offer up a guide or a tutorial of some sort that shows how to customise the wallet?

Just a guide that shows how to change the config , add your own tokens , change  logo and colors etc so you can host the wallet on your own website?

**Comment by GIvanovWaves** [comment]
Hello, unfortunately, we don't have this type of guides, yet.
We have big plans for the next year to make an alternative client with customizable plugins system for that purpose.

For now, if you have some experience in web development, you can modify our code in any way and post it on your own website.

Stay tuned.
