### ISSUE TITLE
my trade history item appearing and disappearing

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesGUI#1096]
Animated gif showing the problem is attached. You see line 01-11 12:56:08 is appearing in the top and then disappearing, and so on infinitely.

![screen recording 2019-01-11 at 13 06 40](https://user-images.githubusercontent.com/1069223/51030840-51ef4a80-15a3-11e9-817c-b41d6981de4c.gif)

**Comment by Jahsus** [comment]
Hello, thank you for the info. It is not a GUI bug, the problem with one of the nodes, we will fix it right now
Thanks again
