### ISSUE TITLE
Deeplinks to Dex Pairs does not work on Waves Desktop Client 1.0.35

### ISSUE THREAD

**Issue by sabotagebeats** [wavesplatform/WavesGUI#1107]
For example: https://beta.wavesplatform.com/dex?assetId2=HzfaJp8YQWLvQG4FkUxq2Q7iYWMYQ2k8UF89vVJAjWPj&assetId1=WAVES does not open anything on waves desktop

**Comment by sabotagebeats** [comment]
as per this: it should work https://github.com/wavesplatform/WavesGUI/issues/302

**Comment by GIvanovWaves** [comment]
Hi, thanks for the feedback.
It seems that redirect from` https://beta.wavesplatform.com` to `https://client.wavesplatfrom.com` loses link query string for deep links.
We will fix that. 
But in future, please use our main URL - https://client.wavesplatform.com

**Comment by GIvanovWaves** [comment]
Fixed.
