### ISSUE TITLE
Sonarcloud

### ISSUE THREAD

**Issue by foerl** [wavesplatform/WavesGUI#1123]
hi there, bill petridis ran your waves-gui through sonarcloud and found 575 bugs and 72 codesmells. will you guys please have a look at this? thank you very much! :) 

https://sonarcloud.io/organizations/bpetridis-github/projects

https://sonarcloud.io/dashboard?id=Waves-GUI

![0000](https://user-images.githubusercontent.com/30558834/52033064-df2f1a80-2523-11e9-9702-b3730b604046.PNG)

I have been using your client for sometime now and found it very nicely done and easy to set up. :)

**Comment by GIvanovWaves** [comment]
Dublicates: https://github.com/wavesplatform/WavesGUI/issues/1084
