### ISSUE TITLE
My balance tab content is not aligned

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesGUI#1140]
When asset ids are combined with aliases, columns aren't aligned properly:
<img width="865" alt="screen shot 2019-02-05 at 12 08 42" src="https://user-images.githubusercontent.com/1069223/52266543-5b1fcd00-293f-11e9-98da-0a295fcc4045.png">

**Comment by GIvanovWaves** [comment]
Hi, we will fix that, thanks.

**Comment by GIvanovWaves** [comment]
Fixed.
