### ISSUE TITLE
testnet client not working

### ISSUE THREAD

**Issue by Bang9** [wavesplatform/WavesGUI#1161]
![image](https://user-images.githubusercontent.com/26326015/52785298-faa93200-309a-11e9-97b1-5044617b4fb6.png)

what happend?

**Comment by Bang9** [comment]
Is it just happend because nothing to show?

**Comment by GIvanovWaves** [comment]
Hi.
Yes, there is no data on the last price of that pair, because there were no trades.
But client app should not throw errors in console, thanks for the report.

**Comment by GIvanovWaves** [comment]
We thought about this and concluded that this intended behavior.
When there is no trade history or any order on asset pair, matcher sends 404 error (Not Found).
