### ISSUE TITLE
Payment api numeric attachment

### ISSUE THREAD

**Issue by w0utje** [wavesplatform/WavesGUI#1190]
when the payment link contains an numeric attachment (some number/id), the send dialog won't be able to send the transaction.
console says: error: uncaught promise: FIELD_ERROR, message: Byte array or Uint8Array input is expected
the dialog buttons won't have the cancel and send texts and some red box will appear in the dialog

![image](https://user-images.githubusercontent.com/24413960/53518826-27653c80-3ad2-11e9-8b2b-e93042ec6a94.png)

reproduce:
https://client.wavesplatform.com/#send/WAVES?amount=10&recipient=3P9e6xQHm251gVzbq3UxjQ95hdiSjccKNzN&attachment=1234567890

workaround: add a single letter to the attachment like A1234567890 or 1234567890A

**Comment by GIvanovWaves** [comment]
Hi, thank you for the feedback, we will fix this in next release.

**Comment by GIvanovWaves** [comment]
Fixed in release 1.1.0
