### ISSUE TITLE
Address on top of wallet screen

### ISSUE THREAD

**Issue by pianist** [wavesplatform/WavesGUI#122]
Please, allow selection of wallet addres and do not copy it to clipboard.

Make additional button "copy" to copy it to clipboard.

**Comment by supereth** [comment]
In which case would be more optimal a partial or manual copy of the address than a complete and automated copy to clipboard function? we can do this but I simply do not see the point.

**Comment by xenohunter** [comment]
@pianist in the new design, that will be done so. Thank you for pointing that out!

**Comment by xenohunter** [comment]
The issue is not relevant anymore, sorry.
