### ISSUE TITLE
Should be no 'Type' in the Trade History

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesGUI#1232]
There is first column '**Type**', but it has no sense - in the common **Trade History** it is always someones **Buy** matched against someone else's **Sell**. Only in **My Trade History** tab this column makes sense - it is **Buy** or **Sell** from my own point of view

**Comment by GIvanovWaves** [comment]
Hello.
On that page, a type is determined by the latest order type.
We decided that it would be useful to know some type of orders in Trade History.
