### ISSUE TITLE
Don't trim trailing zeroes

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesGUI#1304]
Can we please do not remove trailing zeroes, so columns data will be properly aligned?
![Screen Shot 2019-05-07 at 10 36 15](https://user-images.githubusercontent.com/1069223/57282132-18dc6800-70b5-11e9-86d5-0599cb9425c4.png)

**Comment by Jahsus** [comment]
Hello, your request have been approved, and the solution should be released in next version of the client (1.2.8). Thank you, and looking forward for more ideas from you.
