### ISSUE TITLE
Time sorting precision is 1 second

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesGUI#1324]
Both **wallet/transactions** list and **My Trade History** tab have insufficient sorting precision - just one second (and should be millisecond).
There are situations when transactions are out of order.

![Screen Shot 2019-05-27 at 10 22 47](https://user-images.githubusercontent.com/1069223/58403519-8bfd4c80-806b-11e9-9a76-9498f1518ce5.png)
![Screen Shot 2019-05-27 at 10 25 03](https://user-images.githubusercontent.com/1069223/58403641-e4cce500-806b-11e9-817d-70e5d452c030.png)
![Screen Shot 2019-05-27 at 10 25 41](https://user-images.githubusercontent.com/1069223/58403651-e8f90280-806b-11e9-806e-37d1c191a47b.png)
![Screen Shot 2019-05-27 at 10 26 03](https://user-images.githubusercontent.com/1069223/58403660-ed252000-806b-11e9-80f1-702211654016.png)

**Comment by GIvanovWaves** [comment]
Hi, by default our client doesn't sort by timestamp and transactions are shown as they are represented in the blockchain.
Decentralized nature of blockchain cannot guarantee some errors in timestamp differences of transactions, this is why nodes will return tx list in the order they have been put in the blockchain.
But we will discuss the possibility of adding some sorting option.

**Comment by br0x** [comment]
Well, last changes to client stopped to sort by timestamp. Now your client is completely useless. Good luck.
