### ISSUE TITLE
Getting search query length doesnt work in Chrome on Linux

### ISSUE THREAD

**Issue by justjamesdev** [wavesplatform/WavesGUI#1378]
https://github.com/wavesplatform/WavesGUI/blob/07f3436effebf7a72ee0774e1f1ba0659129d414/src/modules/dex/directives/dexWatchlist/WatchList.js#L676

The blob size comes back 5153 

![image](https://user-images.githubusercontent.com/25159913/59428697-3dc3a980-8dde-11e9-8b59-9a79029afa73.png)

**Comment by tsigel** [comment]
Hi! 
Your case is not repeated:
My output (Chrome, Ubuntu):
```
new Blob(['VI'], {type: 'text/html'}).size; // 2
```
Please provide more details.

**Comment by justjamesdev** [comment]
Ok this is on Manjaro linux (Version 74.0.3729.131 (Official Build) Manjaro Linux (64-bit)) 
I wonder if its just something odd with this build then. Why the text/html though? If I remove that (Presumably it defaults to UTF-8 then) Then the length is fine. 

HOWEVER

Now I try what you tried in console and its fine, so only manifests in app.. I wonder if a polyfill or something is changing its behaviour. 

I best do more research

**Comment by justjamesdev** [comment]
Updated Chromium, I was wrong, this is probably a chromium bug I suppose; 

![image](https://user-images.githubusercontent.com/25159913/59437710-5b9b0980-8df2-11e9-924a-5db0c0bf88a0.png)

Version 75.0.3770.80 (Official Build) Arch Linux (64-bit)

Just out of interest though, why the text/html?

**Comment by tsigel** [comment]
We will fix this case, thanks.

**Comment by justjamesdev** [comment]
Ok, I have managed to isolate the cause.. When running this when client.wavesplatform.com is open; 

```
new Blob(['VI'], {type: 'text/html'}).size;
5153
```

When on any other browser tab; 

```
new Blob(['VI'], {type: 'text/html'}).size;
2
```

Chromium have confirmed that this is not a chromium bug

**Comment by tsigel** [comment]
Hello, please, provide more details, because we can't reproduce your issue. Do you have some browser plugins installed ? Try to execute in browser console this command - `console.log(Blob);` and send us the result.

**Comment by justjamesdev** [comment]
Ok so, In a blank tab; 
```
console.log(Blob)
VM51:1 ƒ Blob() { [native code] }
```
In a client.wavesplatform.com tab; 
```
console.log(Blob)
raven.js:58 ƒ secureBlob(...args) {
      const injectableMimeTypes = [
        { mime: 'text/html', useXMLparser: false },
        { mime: 'application/xhtml+xml', useXMLparser: true },
        { mime: 'text/xml'…
```

So.. Why is raven replacing blob in my browser :/

**Comment by tsigel** [comment]
> So.. Why is raven replacing blob in my browser :/

This is real interesting question.
We will be debug and fix this problem.
In my browser Blob is native.

**Comment by tsigel** [comment]
Can you please send us your raven.js file, because we dont use secureBlob in our code at all.  What is ur raven version? url where is it downloaded from? Also try to search by all files in console "secureBlob" and send us the result. Alse disable all plugins in browser. If you dont use Waves Keeper, we recommend you to create new account via Keeper and transfer all valauble assets to the new account.
