### ISSUE TITLE
 Personalized wallet on my server

### ISSUE THREAD

**Issue by Cristyander** [wavesplatform/WavesGUI#1390]
I want to have a custom wallet hosted on my server, but when I deploy it it says it does not find the "gulp". I understand that the gulpfile is only for developers and the application after the build is added to localhost. What files should be changed in wavesgui to deploy on an online server to the end user of my custom wallet?

**Comment by tsigel** [comment]
Hello! 
For fix problem with gulp u need install nodejs package `gulp` as global package. 
Use `npm i gulp -g`.

Your need run `npm run build` and gulp will be create directory `dist` with builds.
`dist/web/mainnet/min` - this folder with client. U can launch `index.html`

**Comment by 0XSFZX** [comment]
> Hello!
> For fix problem with gulp u need install nodejs package `gulp` as global package.
> Use `npm i gulp -g`.
> 
> Your need run `npm run build` and gulp will be create directory `dist` with builds.
> `dist/web/mainnet/min` - this folder with client. U can launch `index.html`

thanks
