### ISSUE TITLE
error in npm i

### ISSUE THREAD

**Issue by hbastidas** [wavesplatform/WavesGUI#1502]
> waves-client@1.3.10 postinstall /Users/user/WavesGUI
> sh scripts/postinstall.sh

run post install script
compile typescript
data-service/store.ts:49:32 - error TS2345: Argument of type '<T, U>(obj1: Record<string, T>, obj2: Record<string, U>) => boolean' is not assignable to parameter of type '(a: T, b: T) => boolean'.
  Types of parameters 'obj1' and 'a' are incompatible.
    Type 'T' is not assignable to type 'Record<string, unknown>'.

49         list => differenceWith(eqProps(idKey), list, toRemoveContainer.map(prop('data'))) as any,
                                  ~~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.3.10 postinstall: `sh scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the waves-client@1.3.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



testing in 

MacOS 10.14.5
node -v = v10.16.0
npm -v = 6.9.0

**Comment by cryptoneobancoin** [comment]
ward

**Comment by tsigel** [comment]
Hello, we fix this problem. 
What the version of typescript in global and in node_modules?
Your can pull the updates.

**Comment by hbastidas** [comment]
wow, I can't reproduce the problem, after deleting the previous git clone and cloning it back to work.
