### ISSUE TITLE
Source code of https://wavesblockexplorer.com/

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#1521]
Do you have source code of https://wavesblockexplorer.com/ ?
If yes, can you publish the link, there?

**Comment by beregovoy68** [comment]
Hey,

Yes, we do have the source code of WavesExplorer before redesign. You can find it here: https://github.com/wavesplatform/WavesExplorerLite/tree/old-explorer

Cheers!

**Comment by username1565** [comment]
Hm... This not working for me.
```Failed to load blockchain info```
But this block explorer is working: https://wavesblockexplorer.com/#!
Do you have the souce code of https://wavesblockexplorer.com , not https://wavesexplorer.com/

**Comment by beregovoy68** [comment]
We don't own wavesblockexplorer.com project. 

Apparently is has been cloned from our repository at some point in time and deployed to this domain. If you're looking for sources for this app, you'd better contact domain owners.

Cheers

**Comment by username1565** [comment]
@beregovoy68, Really, in the branch "old-explorer", there is [this blockexplorer](https://wavesblockexplorer.com/#!), not [that blockexplorer](http://wavesexplorer.com/)
But in README.md there is the same link.
