### ISSUE TITLE
trading view

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#1681]
Trading view for unauthorized users working [here](https://client.wavesplatform.com/#!/dex-demo?assetId2=WAVES&assetId1=8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS), but not working [here](https://dex.wavesplatform.com/dex?assetId2=WAVES&assetId1=8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS).
In the second case, there is redirect to "sign in".
Not all users are registered here, and not for all users can need to be registered to see trading, charts, and candels. For example, while promotion the token in the over-the-counter market.

Also, here: https://tokenrating.wavesexplorer.com/?filter=top&page=1, there is link to dex.wavesplatform.com, and this not working without "sign in".

Fix this plz.

**Comment by vba2000** [comment]
Hello.
1) Links on demo dex is invalid. You can take link as this  "https://dex.wavesplatform.com/dex-demo?assetId2=WAVES&assetId1=8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"  
2) You wallet and dex don't work with out active user. You must login to the wallet.

**Comment by username1565** [comment]
1. You are rigtht, thanks!
Your link is working, and I see the trading view there, without need to "Sign in".
I don't know how to contact them: https://tokenrating.wavesexplorer.com/?filter=top&page=1
maybe you can do this youself to they fix the links there.

2. I didn't ask about trading, I know to do this need to "sign in", but just trading view must to be available for each user, even unauthorized. IMHO.
And after all, no any problems with this, just incorrect links, there.

This issue is closed.
