### ISSUE TITLE
Desktop client

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#1813]
[Here, in `README.md`](https://github.com/wavesplatform/WavesGUI/blob/dev/README.md), I see the following link:

`The desktop client can be downloaded from `[https://wavesplatform.com/product](https://wavesplatform.com/product)

But this link is not working.

Where is possible to download desktop-client, and how to compile this?

**Comment by tsigel** [comment]
This repository is not supported now. Your can clone a repository and build desktop client, or download [here](https://waves.exchange/).
