### ISSUE TITLE
Unable to locate open DEX order

### ISSUE THREAD

**Issue by goforthtech** [wavesplatform/WavesGUI#217]
After creating and completing a number of orders (WAV/BTC); the 'My Orders' pane appeared to fill up and no longer show any new orders that were opened.  Thinking that I just needed to get rid of closed orders for my open order to appear,  clicking the 'x' next to closed orders, they remove from the list but the open order still does not appear.  I now have an order (it's small so no biggy) that is open with no way to close it and the 'My Orders' pane is completely clear.

**Comment by xenohunter** [comment]
Hi, @goforthtech! Thank you for reporting the issue. Sadly, there is such an inconvenience. That is due ti chrome app storage limitations. We have located and fixed it, though, and it's now in testing and will be released in several (maybe a couple of) of days. Hope there was no big trouble with it!

**Comment by goforthtech** [comment]
You the man and no worries!  Just have to be aware until then.  Thanks for the great work!
