### ISSUE TITLE
Select 'Price' in DEX

### ISSUE THREAD

**Issue by goforthtech** [wavesplatform/WavesGUI#218]
When preparing to place an order in the DEX; there is no option to 'select' a price from the open orders.  This leads to manual entry and therefore, error prone.  The ability to select a price from the open order would populate the 'price' fields in the Buy / Sell.

**Comment by xenohunter** [comment]
Do you mean the behavior when you click on the row in a buy/sell orderbook so the order creation form is filled with correlating values? Or is it about clicking some element in user orders list?

**Comment by goforthtech** [comment]
As you mentioned in the first part.  Example:  I look at the order book and see a Buy order for X number of Waves for 0.00040 BTC.  I can click that order; and under 'Sell Waves' portion; the BTC value will auto populate with 0.0040 and then all I have to do is fill in the number of Waves.

Would be nice to also have an option to set the Qty to your current balance max.  Maybe just a little up arrow next to the [currency] Amount.

**Comment by xenohunter** [comment]
We added that in the next release, too. Most part of that behavior, to be precise. There is only no way to fill in the balance max yet. Thanks for the participating!
