### ISSUE TITLE
Feature Request: Change the currencies shown on main Screen

### ISSUE THREAD

**Issue by goforthtech** [wavesplatform/WavesGUI#219]
Would be nice to be able to set the currencies / assets that you would like to have shown on the opening screen.  Not interested in Yuan (for example); but very interested in my created Asset.

**Comment by marsappslab** [comment]
Hello,
Does that feature is in study? I'm also interested.
Thanks!

**Comment by xenohunter** [comment]
Hello! It is postponed at the moment. If there is some news on this, we'll update the issue.

**Comment by GIvanovWaves** [comment]
With Pin/Unpin functionality you can set any token on Asset screen.
Sorry for a late answer.
