### ISSUE TITLE
New Account generation notice mentions a seed "copy" button which doesn't exist.

### ISSUE THREAD

**Issue by outragedhuman** [wavesplatform/WavesGUI#229]
The notice:

![image](https://cloud.githubusercontent.com/assets/6742283/25556939/15571dfe-2cd5-11e7-8567-367fd8424264.png)

The lack of copy button (seed removed for security):

![image](https://cloud.githubusercontent.com/assets/6742283/25556944/22767b4c-2cd5-11e7-9eaf-e42db5bfd99c.png)

EDIT: Just in case this is a browser issue. The screenshots came from Chrome Version 57.0.2987.133 (64-bit)

**Comment by xenohunter** [comment]
Hi, and thank you for reporting the issue! I guess it's just a text inconsistency as there was no copy button on the login screen, if I remember correctly. I'll recheck it tomorrow though.

**Comment by outragedhuman** [comment]
Sure thing @xenohunter 

A copy button would be a good idea, but the field does allow easy selection of the entire seed. Your average user might appreciate a one-click option though to avoid missing a character or two at the ends of the seed.

**Comment by xenohunter** [comment]
I think it would be better to postpone that a little as far as we're going to refactor the client and apply the new design to it. I'll mark the issue as an enhancement and start is as soon as a component for a seed is created.

_Idea for future development: in the seed widget, aside from a textarea itself, create a tiny bar stuck to the bottom of the textarea which shows total length, estimate entropy and contains a copy button._

**Comment by xenohunter** [comment]
The seed can be copied in the new beta client (https://beta.wavesplatform.com).
