### ISSUE TITLE
Cannot see last asset

### ISSUE THREAD

**Issue by yelllowsin** [wavesplatform/WavesGUI#233]
It is impossible to scroll down or up the assets on the lite client. See attached image.
![no_scroll](https://cloud.githubusercontent.com/assets/7217595/25713601/a9ff7fa6-30cb-11e7-9665-b21b4f4484af.jpg)

**Comment by yelllowsin** [comment]
Well, actually you can scroll down. But the last asset does not completly appear. Guess this is the issue.

**Comment by xenohunter** [comment]
Hello! Thanks for reporting. Fixed in [that](https://github.com/wavesplatform/WavesGUI/pull/234/commits/5335117ad39237c6fab647b74911bec3047990c3) commit.
