### ISSUE TITLE
Order not shown under "My Orders" 

### ISSUE THREAD

**Issue by ScevolaDandera** [wavesplatform/WavesGUI#250]
Orders placed are not shown under 'My Orders'.
Orders are properly placed since it can be seen on "Sell Orders" or "Buy Orders" List.
Amount for the order is deducted accordingly.

Tested both on Lite Client 0.4.23a and also on waveswallet.io

In case if you want to cancel the order, it is not possible now. 
Scenario: Price Mooned too high and possibly won't come down to trigger a Sales Order in a near Future

**Comment by xenohunter** [comment]
Since v0.4.22, orders are stored in the matcher and requested from there. There may be a bug in the [matcher](https://github.com/wavesplatform/Waves/tree/master/src/main/scala/com/wavesplatform/matcher) itself. Though I can mention @koloale who knows much more on the subject.
