### ISSUE TITLE
Unhelpful  Error Msgs

### ISSUE THREAD

**Issue by ScevolaDandera** [wavesplatform/WavesGUI#251]
Not a single error msg is helpful.
eg. Order has not been created

It can be due to network issue, due to insufficient balance or any.

If a mechanism to log errors by giving it a reference, users can report bugs easily.

**Comment by xenohunter** [comment]
Thank you for the feedback! The more sophisticated error handling will be introduced right after the new design. There is some legacy remained from the early prototype which will be dealt with soon.

**Comment by myalcin81** [comment]
up here.

**Comment by xenohunter** [comment]
Hey! We're still working on it. Some messages are on [beta.wavesplatform.com](https://beta.wavesplatform.com/) already.

**Comment by xenohunter** [comment]
Most errors are now handled properly in the beta Waves Client: [beta.wavesplatform.com](https://beta.wavesplatform.com/).
