### ISSUE TITLE
Issues with 4.23

### ISSUE THREAD

**Issue by b2bloomfield** [wavesplatform/WavesGUI#252]
Hello few issues outlined with 4.23a client:

Popup states cannot get balance
*0* blocks after today @4pm CST will load 50/50 after log out log in
No transactional history
Unable to get leasing information dialogue states unable to get balances
Incoming transfer hangs

**Comment by xenohunter** [comment]
Hi! There was an overload over the Waves network around that time. That is not a Lite Client issue. Although thank you for the feedback!

**Comment by b2bloomfield** [comment]
Cool deal thank you

Thanks,
B
