### ISSUE TITLE
feature request: remember last choices on DEX tab

### ISSUE THREAD

**Issue by mowliv** [wavesplatform/WavesGUI#256]
When I change away from DEX tab and come back it has forgotten my token choices. Please change so that persists when I switch tabs, and ideally also persists even if I quit the app and restart it.

**Comment by xenohunter** [comment]
Thank you for the proposal, we will make it so the last pair is remembered even when you import your account and unwrap it on another device (the import feature is planned, too).

**Comment by mowliv** [comment]
wow, even better!

**Comment by xenohunter** [comment]
Hello! The pair choice is preserved now in the beta Waves Client: https://beta.wavesplatform.com.
