### ISSUE TITLE
feature request: open orders list across tokens

### ISSUE THREAD

**Issue by mowliv** [wavesplatform/WavesGUI#257]
I can only see what orders I have open in the My Orders list when I enter the right two currencies at top of DEX page. Please add a feature so I can see all open orders across all tokens somewhere (without having to enter the currency pairs to see). Thanks!

**Comment by xenohunter** [comment]
Thank you, we will add this feature after implementing the new design.

**Comment by xenohunter** [comment]
Hello! It's done: https://beta.wavesplatform.com/dex.
