### ISSUE TITLE
Order can minus waves

### ISSUE THREAD

**Issue by SuwandiSlasher** [wavesplatform/WavesGUI#262]
Sometime i order too quickly, and my waves become minus and the order is placing on buy orders right away. I have experience this twice. I have never waited until my orders were successfully exchanged, so i cancel it asap too.

**Comment by xenohunter** [comment]
Hi and thanks for reporting! We will check and fix it.

**Comment by SuwandiSlasher** [comment]
look like the bug flow like this,
assume my waves is 30,
i create buy order using 20 waves,
so my remaining waves is 10 waves,
when someone sell some asset total 20 waves to my buy order,
my waves balance will auto refresh to 30 waves for temporary,
then i can recreate order for 20 waves.
now my waves is -10.

Note:
this is just my assumption, hope it will help.

**Comment by xenohunter** [comment]
Thank you, that is helpful. I guess that is an issue with the [matcher](https://github.com/wavesplatform/Waves/tree/master/src/main/scala/com/wavesplatform/matcher). Maybe @koloale could help us.
