### ISSUE TITLE
Orderbook bug. Maybe matcher issue. 

### ISSUE THREAD

**Issue by nbkshocks** [wavesplatform/WavesGUI#265]
![image](https://user-images.githubusercontent.com/29697494/27522408-9f107b44-59da-11e7-9de8-528072a0ec4c.png)

![image](https://user-images.githubusercontent.com/29697494/27522432-da248644-59da-11e7-840c-552abadeb317.png)

I bought some mercury, 40k amount but not seeing it in my order page.. This is happening with waveswallet.io/liteapp/mainnet. Firewall/anti-virus were off. Please help.

**Comment by xenohunter** [comment]
Hello! This is a matcher issue indeed. Please try contacting @koloale. You may create an issue in the [Waves repository](https://github.com/wavesplatform/Waves). Thank you for sharing it anyway!
