### ISSUE TITLE
Dialog will disappear when click withdraw not in full screen

### ISSUE THREAD

**Issue by SuwandiSlasher** [wavesplatform/WavesGUI#276]
screen resolution : 1366x768
set app to restore down (not full screen)
click withdraw bitcoin or ethereum.
The dialog will appear for a moment.

**Comment by xenohunter** [comment]
Hello! Yes, that's a known bug though not easy to reproduce. It will be fixed with the new design.

**Comment by dlepold** [comment]
until then i managed to make it work in FIREFOX ;) 
Try Firefox if u need it urgently.

**Comment by dlepold** [comment]
p.s. i think this is a severe problem for people who want to transfer their assets and can't not good publicity. I mean, no prob with a temp. bug, but this is exisiting for quite a long time already .... Best wishes

**Comment by xenohunter** [comment]
Fixed in 8b2a5808473a71e564331d661f858bb8b58298ce.
