### ISSUE TITLE
Is this working with Ubuntu?

### ISSUE THREAD

**Issue by aphilsmith** [wavesplatform/WavesGUI#277]
Strictly following the README.md, it installs on Ubuntu 16.04, all dependencies are installed and grunt completes. The WavesGUI path is linked to /var/www/html/WavesGUI and I tried the URL http://myhost/WavesGUI/src, but the web page has Address: {{::menu.address}} overlayed and is in incomplete. Perhaps there is another undocumented step?

**Comment by xenohunter** [comment]
Hello! I guess you should link your server to _/var/www/html/WavesGUI/distr/mainnet_ once it's built.
