### ISSUE TITLE
Multisignature wallets

### ISSUE THREAD

**Issue by Gim6626** [wavesplatform/WavesGUI#280]
Hi!

Is multisignature feature available in Waves? Could not find nothing like it in Lite GUI. I've read that this feature is available for Bitcoin and wanted to know is it available or maybe planned for implementation here.

Thanks in advance

**Comment by xenohunter** [comment]
Hello! There is no such feature yet but it's planned for some future time. I guess you better stay tuned to [Waves Core repository](https://github.com/wavesplatform/Waves) as it will be implemented there first.
