### ISSUE TITLE
Drop scientific formatting

### ISSUE THREAD

**Issue by biolypl** [wavesplatform/WavesGUI#283]
I propose change the number formatting to 8 decimal places in trading tab and elsewhere else, scientific format is unreadable for average user. Example: 
![selection_003](https://user-images.githubusercontent.com/19519175/29705852-175e167c-8980-11e7-83eb-83708cd29a85.png)
To reproduce scientific format for buy/sell view, just click any offer from offers table

**Comment by xenohunter** [comment]
Dropped in https://github.com/wavesplatform/WavesGUI/pull/290.
