### ISSUE TITLE
Automatic check for new version

### ISSUE THREAD

**Issue by waves100** [wavesplatform/WavesGUI#284]
When starting the lite client, it should be checked, if a newer version than the current version exists. If this is the case, an appropriate message should be shown. Otherwise many users don't know about new versions and report errors which are already fixed or can't use new functionality which is already implemented.

**Comment by onurgozupek** [comment]
When you relaunch Google Chrome client it checks and update the extensions automatically. It's not yet available in HTML version.

**Comment by waves100** [comment]
Yes. I should have specified it better: I'm talking about the manually installed html lite client.

**Comment by xenohunter** [comment]
Thanks for the proposal. We are considering that already to be added in the new Waves Client.

**Comment by xenohunter** [comment]
Hello! We added that to the beta Waves Client: https://beta.wavesplatform.com.
