### ISSUE TITLE
2х факторная авторизация

### ISSUE THREAD

**Issue by Vlaholod** [wavesplatform/WavesGUI#286]
Возможно ли ввести подключение 2х факторной авторизации для обеспечения большей безопасности т.к при сохранении аккаунта он в кукис , в свою очередь если чистим кукис, то каждый раз необходимо вводить сид, что есть не удобно и абсолютно небезопасно.

**Comment by xenohunter** [comment]
Да, мы планируем это сделать в ближайшем будущем.
Yes, we plan to release 2FA in the near future.

**Comment by Vlaholod** [comment]
Спасибо за быстрый ответ.
Thx for the quick response

**Comment by xenohunter** [comment]
It is duplicated in https://github.com/wavesplatform/WavesGUI/issues/435.
