### ISSUE TITLE
official testnet doesn't works

### ISSUE THREAD

**Issue by dotneet** [wavesplatform/WavesGUI#288]
Currently official testnet site doesn't work for me. https://testnet.waveswallet.io/
I can see these errors within console. 

```
VM148:1 Mixed Content: The page at 'https://testnet.waveswallet.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://52.30.47.67:6869/blocks/height'. This request has been blocked; the content must be served over HTTPS.


(anonymous) @ VM148:1
(anonymous) @ waves-lite-client-testnet-0.4.37.js:23456
sendReq @ waves-lite-client-testnet-0.4.37.js:23189
serverRequest @ waves-lite-client-testnet-0.4.37.js:22941
processQueue @ waves-lite-client-testnet-0.4.37.js:27748
(anonymous) @ waves-lite-client-testnet-0.4.37.js:27792
$digest @ waves-lite-client-testnet-0.4.37.js:28930
$apply @ waves-lite-client-testnet-0.4.37.js:29228
tick @ waves-lite-client-testnet-0.4.37.js:24071
```

And I've tested the latest testnet distributeion in this repository (waves-lite-client-testnet-v0.5.1.zip), but some errors is displayed in console. Maybe it causes a some bugs in exchange screen. I can't find the token that is issued by myself.

this is a message that is displayed in console.

```
https://testnet1.wavesnodes.com/matcher/orderbook/WAVES/xxxxx/publicKey/xxxxx 404 ()
```

```
Failed to load https://testnet1.wavesnodes.com/matcher/orderbook/WAVES/xxxxx/tradableBalance/xxxxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by xenohunter** [comment]
Hey! Thanks for reporting. The issue at https://testnet.waveswallet.io is fixed though there are some server-side issues still. We will fix them ASAP.

**Comment by xenohunter** [comment]
Testnet is fully intact now, please check: https://testnet.waveswallet.io.

**Comment by dotneet** [comment]
@xenohunter 
Thanks!
but I still have saw same error in console and exchange screen is not displayed. 
So, disabling cache and removing local storage, I've tried to display exchange screen again, but had same result.

```
Mixed Content: The page at 'https://testnet.waveswallet.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://52.30.47.67:6869/blocks/height'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by xenohunter** [comment]
That's strange. Could you make it sure that the version of the testnet wallet is 0.5.1?

**Comment by dotneet** [comment]
The version displayed in screen is 0.4.37a.
![screen](https://user-images.githubusercontent.com/370602/30068451-cf8b2638-9298-11e7-8395-23070c8b9cbf.png)

**Comment by dotneet** [comment]
I think this is a problem related to CDN.
I'm accessing the site from japan but you are in another location, so CDN's response is different.
If my thought is correct and you could remove the cache from CDN, this problem would be resolved.

**Comment by dotneet** [comment]
I've tested local version. that works well!! thanks!

**Comment by dotneet** [comment]
Hi @xenohunter,
Official testnet is fully intact now!
CDN cache seems to be refreshed! Thanks!

**Comment by xenohunter** [comment]
Hello, @dotneet! Great to hear, I hope you have nice experience with the wallet!
