### ISSUE TITLE
Releases page link

### ISSUE THREAD

**Issue by onurgozupek** [wavesplatform/WavesGUI#293]
Can you relink Releases page ( https://github.com/wavesplatform/WavesGUI/releases ) as it's not linked anymore and I'm using HTML version instead Google Chrome Extension, it became hard to find :)

**Comment by xenohunter** [comment]
Hello! Could you tell where exactly it was linked?

**Comment by onurgozupek** [comment]
It was previously linked under Downloadable Distrubutions ( https://github.com/wavesplatform/WavesGUI#downloadable-distributions ) 

In the first sentence it says "Here in the Releases page you can find all Lite Client packages available for download." but the "Releases page"  is not linked to the releases page. (and I'm sorry, I didn't notice that the Releases link was on the top of the file list table)

**Comment by xenohunter** [comment]
Hey! Thanks for the explanation. I added it in 0b992273fadbb3d09c2cd004936646feff61ceb6.
