### ISSUE TITLE
[Request] DEX pair shortcut links

### ISSUE THREAD

**Issue by robally215** [wavesplatform/WavesGUI#299]
On the DEX, please have shortcut links to coins we hold, as you do with BTC,ETH,USD, etc.
Example: I own kross and EOT , I load the dex up . on the right there will be entry into pair kross/waves -  EOT/waves, etc. Or the ability to save pairs.
Thanks.
Great platform!

**Comment by xenohunter** [comment]
Hello and thanks for the contribution! We are working on the new Waves Client version, and the UI will be absolutely different. We will consider your request, of course. Thank you!

**Comment by xenohunter** [comment]
Hello again! We have that feature already. For example, that link — https://beta.wavesplatform.com/dex?assetId2=HzfaJp8YQWLvQG4FkUxq2Q7iYWMYQ2k8UF89vVJAjWPj&assetId1=WAVES — will lead you to the MER/WAVES pair. All you need to share such a link is to copy the URL of an active pair.
