### ISSUE TITLE
Feature request: Deeplinking to DEX and other pages

### ISSUE THREAD

**Issue by jasny** [wavesplatform/WavesGUI#302]
It would be great if we could link directly to a specific pair on the DAX, like  https://waveswallet.io/#!/dex/waves-btc

Typically the user needs to login or create a wallet first. When that's done, he should be taken to the specific pair in the DEX view.

This will make it easier to link to buying your coin, not having to rely on screenshots to explain.

Other pages could also enjoy having associated locations like https://waveswallet.io/#!portfolio.

**Comment by jasny** [comment]
If appreciated, we can supply a pull-request.

**Comment by xenohunter** [comment]
Hello and thank you for the request! We are working on the absolutely new version of Waves Client and will add that feature in it.

**Comment by xenohunter** [comment]
Hello! The routing inside the app is working already. For example: https://beta.wavesplatform.com/dex?assetId2=HzfaJp8YQWLvQG4FkUxq2Q7iYWMYQ2k8UF89vVJAjWPj&assetId1=WAVES.
