### ISSUE TITLE
Feature request: Transactions with amount of zero 

### ISSUE THREAD

**Issue by exelletor** [wavesplatform/WavesGUI#305]
It would be great to have a possibility in the client to send transactions with amount of zero waves or any other asset and just pay the transaction/miners fee. This can come in handy when you just need to share a certain attachment or in the future, a execute a smart contract. Personally i was thinking about a voting mechanism simillar to Mothership Governance feature.

**Comment by xenohunter** [comment]
Hey! I'm not sure that would be the expected behavior. More than that, it's not possible to create a zero amount transaction even on the API level. If you're eager to have that transaction try to drop a feature request to [wavesplatform/Waves](https://github.com/wavesplatform/Waves).
