### ISSUE TITLE
use https for links (and not http)

### ISSUE THREAD

**Issue by MeInTheFuture** [wavesplatform/WavesGUI#320]
see pic:
* the website supports https

WavesGUI version: 0.5.8

<br><br>

![http_only](https://user-images.githubusercontent.com/33371684/32453537-c1212f84-c31c-11e7-8b64-99264f4facf1.png)

**Comment by xenohunter** [comment]
Hello! Thanks, we'll fix it soon.

**Comment by xenohunter** [comment]
Hello! Sorry for the long delay. It's done here — https://github.com/wavesplatform/WavesGUI/commit/3c432da1880d7723aa1bf46983526bbe07b31460 — and will be released in due time.
