### ISSUE TITLE
Non verified assets dont show in DEX

### ISSUE THREAD

**Issue by bhok** [wavesplatform/WavesGUI#322]
I would like to know what is the plan about the non verified assets, with 0.5.9 they can not be sold or bought in the dex, there are some plan to relist them? or only will be tradable verified assets?, what is the plan about it?

**Comment by xenohunter** [comment]
Hello! The idea is to protect our users from scam assets. Every asset is available on DEX by its ID. The following steps are needed to have the wanted pair:
1. Get the ID from asset details on portfolio page (or get it from any trusted source).
2. Paste it in any of the two search fields on DEX page.
3. Click the dropdown menu item with that ID on it.
