### ISSUE TITLE
sending bitcoin cash problem

### ISSUE THREAD

**Issue by italy2010** [wavesplatform/WavesGUI#327]
when i want send bcc to my bittrex wallet say me that invaild address  02 erorr. why?

**Comment by xenohunter** [comment]
Hello! I guess you'd better visit [support.wavesplatform.com](http://support.wavesplatform.com/) and contact our support managers. Also, the address you're trying to use may be invalid indeed.

**Comment by italy2010** [comment]
address is from bittrex and vaild.
