### ISSUE TITLE
 SyntaxError: Use of reserved word 'class'

### ISSUE THREAD

**Issue by johanfriso87** [wavesplatform/WavesGUI#388]
I download newest version from git and try to build it.
Command "" is successfully completed, but "grunt distr" makes following error.
I don't know why this error occurs
my npm version is 3.10.10.
I'd appreciate if you could fix this error.

PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Use of reserved word 'class'
  at E:/Projects/171204_Pure/01_ref/02_Dex/Waves/WavesGUI/WavesGUI-0.5.10/bower_components/growl/javascripts/jquery.growl.js:14

Warning: Task "karma:development" failed. Use --force to continue.

Aborted due to warnings.

![image](https://user-images.githubusercontent.com/31540630/33975586-af61eda2-e08f-11e7-941d-711f9afc1d90.png)

**Comment by xenohunter** [comment]
Hello! That's strange. Are you on `master` branch?

**Comment by johanfriso87** [comment]
No.

**Comment by xenohunter** [comment]
Then what branch are you at? Grunt should not be used on any branch besides master.

**Comment by xenohunter** [comment]
Fixed in e8c32d3e23bb667cd77df64244681975ae715b3d.
