### ISSUE TITLE
Private methods usage for matcher

### ISSUE THREAD

**Issue by voldemarpro** [wavesplatform/WavesGUI#396]
Hi, i'd like to use core services to explore order history from several addresses (all mine). Should i request orderbook by public key, as far as working with address requires api_key? I can't see any header settings in the source code.  Default api key ridethe**** from mainnet config is not actual one (tested via curl).  Thanks.

**Comment by xenohunter** [comment]
Hello! You could use [waves-api](https://www.npmjs.com/package/waves-api) library. There are methods to get user orders either [by pair](https://github.com/xenohunter/waves-api/blob/master/src/api/matcher/v1/orderbooks.ts#L79) or [altogether](https://github.com/xenohunter/waves-api/blob/master/src/api/matcher/v1/orderbooks.ts#L97). Here's an example:
```
const Waves = WavesAPI.create(WavesAPI.MAINNET_CONFIG);
const s = Waves.Seed.fromExistingPhrase('your seed');
const p = Waves.API.Matcher.v1.orderbooks.getOrders('token-id', 'token'id', s.keyPair);
p.then((orders) => console.log(orders));
```

**Comment by voldemarpro** [comment]
OK, i missed this option as it needs .ts compilation. I did it, but found
1) npm version 5+ requires package.json to be in the root (home) directory
2) npm refuses installation of package with name "waves-api" under a package also called "waves-api"
(self-dependency err) So, one should change package name in json file to any distinct one, and it will work.
