### ISSUE TITLE
Wrong GUI design?

### ISSUE THREAD

**Issue by 9teZQ** [wavesplatform/WavesGUI#409]
Does the GUI design depicted on the website actually exist anywhere?

![image](https://user-images.githubusercontent.com/30100625/34465890-326dd858-ee7f-11e7-833c-04d8d822b95d.png)

**Comment by xenohunter** [comment]
Hello! Sorry for the delay in answering. That design is available at [beta.wavesplatform.com](https://beta.wavesplatform.com/). Only in doesn't work on smartphones yet.
