### ISSUE TITLE
Any way to change theme?

### ISSUE THREAD

**Issue by lonnieOST** [wavesplatform/WavesGUI#433]
Hello, 

I am new to WAVES but am excited about the development.

I registered and logged into the beta site but was wondering if there is any way to change the theme easily?

Cheers,
Lonnie

**Comment by xenohunter** [comment]
Hello, Lonnie! There is no way to change the theme yet. Though you can fork the repository, change the color variables in _/src/modules/config.less_ and build the project from the source files.
