### ISSUE TITLE
Use This Wallet in private blockchain

### ISSUE THREAD

**Issue by renickj** [wavesplatform/WavesGUI#465]
Hi, I tried to re-configure the TESTNET settings to direct to private blockchain.
I am able to create new account but other functionalities doesn't seems to be working with custom/private node. Is it possible to configure private block chain in this wallet or should we write our own?

**Comment by renickj** [comment]
I have modified the mainnet configuration code and node in meta.json file in ts-scripts folder 
Now I could integrate blockchain. 
If someone confirm this please.

**Comment by xenohunter** [comment]
Hello and sorry for the long delay. Are you still facing any problems?

**Comment by renickj** [comment]
I just wanted to confirm whether the meta.json is the right file to modify for private chain or do we have anyother configuration.

**Comment by furiousteam** [comment]
did you managed to connect your private chain ? I have changed the node url but i'm not able to connect. More documentation would be welcome ;)

**Comment by xenohunter** [comment]
@renickj yes, the _meta.json_ file is the correct one.

@furiousteam currently, the beta client use not only the node API but also an API with some aggregated data concerning the blockchain. We are developing a solution which will make it possible to set up such an API for any given node or private blockchain. Though that is without ETA at the moment.

**Comment by 0xae** [comment]
@xenohunter any updates on the api release? the oficial waves wallet is still useless on a private blockchain, the dex doesnt work at all either. When i try to run the wallet and the dex on a private blockchain on localhost only the lease and transactions list work, the rest doenst work .
I've raised the issue #581 with more details. any help is appreciated thank you

**Comment by xenohunter** [comment]
Hello, @0xae. We're still working on it, and that task is not one to be done quickly. I hope we finish it in a reasonable time.

**Comment by Bitcoinera** [comment]
Hi. I am not able to connect to my private blockchain. I wonder if it hast to do with the matcher parameter at configurations.mainnet.matcher. Or should I simply upgrade the api version? By default shows "v0". Any help appreciated.

**Comment by xenohunter** [comment]
@Bitcoinera, please, create a new issue with your detailed question.
