### ISSUE TITLE
Version Control for WavesGUI

### ISSUE THREAD

**Issue by EvertonMelo** [wavesplatform/WavesGUI#486]
@hi guys, 

my name is Everton Melo, 

but my brow Guilherme D, 

want to know why you do not version control this software. ( Waves GUI ) 

font: https://github.com/wavesplatform/WavesGUI/milestones

version control good habits for Softwares.

font: https://en.wikipedia.org/wiki/Version_control

is there any operational reason why this does not happen?

a software without version control, how do you know what is legacy, or even if there are 0-day vulnerabilities

thanks in advance,

I think the waves projects fabulous, I hope you guys see my suggestions.

**Comment by beregovoy68** [comment]
Hi

This is github and it uses [git](https://git-scm.com/) as a version control system. 
So don't worry, we're good at using modern software development practices.

Cheers

**Comment by EvertonMelo** [comment]
@beregovoy68 

Благодарим вас за отзывы.

I do not doubt the intentions of the project, but I can not find evidence of what you say in the public repositories.

example.

if there is only one version in production and others in a private repository, in practice there is only the production version.

so this is not good practice,

other points like suggesting improvements to a software that we do not have free access, to test, would have to do this in mainnet?

**Comment by xenohunter** [comment]
Hello. If you're looking for the Node repo, it is here: https://github.com/wavesplatform/Waves. Everything we use in the Client development is open source, except for TradingView library. However, that doesn't affect the project and you (or anyone else) can easily run our code from source code.

If that's what you seek, the version of the Client is pointed out it the _package.json_ file.

**Comment by EvertonMelo** [comment]
@xenohunter 

Did not read anything I asked?

I know where the production software is,
I want to know if there are legacy and / or alpha or beta versions.

PR are for production only.

As you closed the issue I do not think I wanted to talk about it.
