### ISSUE TITLE
Non-reissuable token incorrectly marked as reissuable

### ISSUE THREAD

**Issue by jasny** [wavesplatform/WavesGUI#491]
We first created only a small amount LTO as a reissuable token. Then we created a larger amount and made the token non-reissuable.

The old wallet correctly shows it as non-reissuable, but the new wallet incorrectly show it as reissuable.

![screenshot-waveswallet io-2018 02 27-14-27-56](https://user-images.githubusercontent.com/100821/36731281-8d3feaa0-1bca-11e8-8b6f-0498e6b6e8a3.png)

![screenshot-beta wavesplatform com-2018 02 27-14-25-12](https://user-images.githubusercontent.com/100821/36731135-12e4e1ac-1bca-11e8-865b-a702d9989c64.png)

**Comment by xenohunter** [comment]
Hello, and thank you for the bug report! We'll try to fix it ASAP.

**Comment by xenohunter** [comment]
Hello again! Please, could you check if the issue still persists?

**Comment by jasny** [comment]
The issue has been solved
