### ISSUE TITLE
How to use beta GUI wallet with private blockchain ?

### ISSUE THREAD

**Issue by furiousteam** [wavesplatform/WavesGUI#497]
Any informations regarding how to use the new beta wallet with private blockchain please ?
What about the beta client version for Mac, Linux and Windows ? How can we compile it ?

Thank you.

**Comment by beregovoy68** [comment]
Hi furiousteam,

I think client development team will answer your question about beta client settings when they have some free time.

Regarding desktop client build, you can take a look at this [page](https://github.com/wavesplatform/WavesGUI/blob/master/build-native.md). The main point here is that you need an Apple developer certificate to sign Mac OS desktop app, and windows application sign certificate for windows app. You can build desktop versions without certs, however users will see annoying system warnings like "This software comes from an untrusted source. Are you sure you want to install it?". I don't thing many users will agree to install this kind of app on their machine.

Cheers

**Comment by furiousteam** [comment]
Hello beregovoy68 thank you for the link really nice. The only problem right now is how to setup the beta wallet for private blockchain based on waves. No luck so far. I'm looking forward to the development team response ;) thx again.

**Comment by xenohunter** [comment]
Hello! Sorry for the long delay, there's a lot of work here. In order to connect the client to a private blockchain, you should:
1) edit settings in _ts-scripts/meta.json_ file;
2) run `npm i` and `npm run server`.

For the details of how to build desktop versions of the client, please look into _package.json_ file, the section `"scripts"`, you'll need those starting with `electron`.

**Comment by furiousteam** [comment]
thank you for the response. I tried to modified the  ts-scripts/meta.json file; but so far no luck i'm not able to connect to my private blockchain. Is there any other files or config do i need to setup please ? Thank you.

**Comment by Bitcoinera** [comment]
More documentation on this subject would be so much appreciated. Not even in the waves forums I could find any info on this.
