### ISSUE TITLE
Deployment Problems

### ISSUE THREAD

**Issue by cyberience** [wavesplatform/WavesGUI#515]
The Documentation on Deployment is a little to Thin.
We have deployed to AWS, but even though we struggled through a few Node packages out of date, we have a running Node, but then we are unable to connect to this node. A tutorial or guide to walk people through would be welcome, with some explanations on whats happening, and how to customise the Wave Client.

**Comment by xenohunter** [comment]
Hello! Most of it is covered here: https://github.com/wavesplatform/WavesGUI/issues/497#issuecomment-372594518. If you have further problems, please reopen this issue.

As to the docs, we will update them soon. Thanks!
