### ISSUE TITLE
[UX] Consider making modal close button hitbox a bit larger

### ISSUE THREAD

**Issue by pzmarzly** [wavesplatform/WavesGUI#526]
I keep missing the close button by few pixels, consider making it a bit larger that it looks. Of course it's possible to close the modal by clicking outside of it, but it doesn't feel right sometimes.

**Comment by Jahsus** [comment]
Hello, yes the hitbox will be enlarged soon
Thank you for yours feedback ;)

**Comment by GIvanovWaves** [comment]
There are some popups with smaller close button, marking as a bug.

**Comment by GIvanovWaves** [comment]
It took us more than a year, but we finally did it! :)
All crosses should be with consistent click area. #1228
