### ISSUE TITLE
Feature Request: Add Ethereum Tokens

### ISSUE THREAD

**Issue by cyberience** [wavesplatform/WavesGUI#555]
We need to be able to add Ethereum Contract addresses that are ERC20 and 223 compliant, so ICO offerings can be viewed and transferred in the wallet, As the exchange may be a bigger problem, these can be exceptions to the exchange until that functionality is in. Although Ethereum may be a competitor to Waves, in fact Waves is superior due to its DEX, and by adding these feature, the user base will expand exponentially.

**Comment by jasny** [comment]
When you're trading Ethereum on Waves, you're actually trading `$WETH` tokens, a Waves asset that is back by Ether. The Ethereum is locked (in a smart contract?) by the payment gateway.

To be able to trade ERC20, the Ethereum gateway also needs to support ERC20 tokens, for which it automatically needs to create Waves assets.

**Comment by xenohunter** [comment]
@jasny, thank you for supporting us, and for the explanation too!
