### ISSUE TITLE
Repository for the marketdata api

### ISSUE THREAD

**Issue by 0xae** [wavesplatform/WavesGUI#581]
Hi there, i want to run the wallet/exchange on my own network so where can i find the repo that runs https://marketdata.wavesplatform.com/api/ ?
Is it open source ?
Thanks in advance

**Comment by 0xae** [comment]
Also, the wallet is making requests to  (/ticker/WAVES/8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS) but the matcher clearly has not an endpoint to handle such request, which suggests that maybe something else is handling it.
Thanks, waiting for your reply

**Comment by xenohunter** [comment]
Hello! I guess you'd better reach out via our community managers and moderators in Slack or Discord channel. This is a developer repository, we are working on the client only. The marketdata service is a standalone one and is developed by other people from community. I'm not sure I know how to find them.
