### ISSUE TITLE
Is 1W really necessary? IMO it only creates confusion.

### ISSUE THREAD

**Issue by bcdev-** [wavesplatform/WavesGUI#60]
> does it make sense to require the "1W" prefix everywhere for public keys? /addresses/balance needs it without 1W, same confusion when transfering from lite client to bittrex and back
> Quote by marilyn4325, I agree 100%.

We need to decide one way or the other, right now it creates unnecessary confusion. I suggest just scrapping 1W, since that's the way Bittrex does it.

**Comment by bcdev-** [comment]
It looks like Sasha is on board:
```
sasha
8:42 AM yes
8:43 we'll just drop it
8:43 the best way out out of this
8:43 I mean 1W
```

**Comment by beregovoy68** [comment]
We discussed this earlier this week and decided to get rid of this prefix. The only question is when this should be announced and implemented. 

Sasha will let you know about the schedule.

**Comment by bcdev-** [comment]
Don't worry, I'm from backend. I don't need to know.
I just needed an ACK that it's on the radar.

Obviously this needs to be implemented somewhere before the first mainnet release. :-)

**Comment by beregovoy68** [comment]
It's gonna be done in the upcoming release. For details see https://github.com/wavesplatform/WavesGUI/commit/8ab2ddd81b8bc25d0eb86fd11b6e77b0b311bfa6
