### ISSUE TITLE
Angular2+ update

### ISSUE THREAD

**Issue by nihalmpatel** [wavesplatform/WavesGUI#603]
It'd be better to have this amazing GUI client upgraded to Angular2+ than the Angular js.

**Comment by Jahsus** [comment]
Hello!
We are WavesGUI uses AngularJS, and Anglular2 and above is completely another technology
So it's not so easy to upgrade, simply it will cost us to make a completely new project and the same time as to rewrite it on React or other morern framework.
Hope you understand ;)
