### ISSUE TITLE
run instructions

### ISSUE THREAD

**Issue by benjyz** [wavesplatform/WavesGUI#61]
would be nice to have some info in the readme how get the client going.

**Comment by beregovoy68** [comment]
Sure. Going to add some docs in November.

**Comment by LucaPaterlini** [comment]
still waiting :) with a link to a pool that mine KAYI =-)

**Comment by beregovoy68** [comment]
@LucaPaterlini We have README.md where I've described how to build client from sources and how to deploy and run a release version.
What in particular makes you unhappy with these docs?
