### ISSUE TITLE
Code is setup for Testnet not Mainnet like description says

### ISSUE THREAD

**Issue by ptr-crypto** [wavesplatform/WavesGUI#63]
See https://github.com/wavesplatform/WavesGUI/blob/master/js/waves.settings.js

Also when setup to testnet it might be helpful to show in red text that it's testnet (so people don't accidentally send real waves to their testnet address).

**Comment by beregovoy68** [comment]
Yes, testnet is the default configuration. On build several packages are created. One of them is for testnet (as sources). The other one is for mainnet. The last one is for chrome browser plugin.

Please see https://github.com/wavesplatform/WavesGUI/blob/master/Gruntfile.js for more details

When it comes to mixing up testnet and mainnet, backend validates the address on API calls. So you'll get an error from backend if you try to send waves from testnet to mainnet and vise versa.
