### ISSUE TITLE
Hide assets (private blacklist)

### ISSUE THREAD

**Issue by jasny** [wavesplatform/WavesGUI#632]
It would be nice if you can blacklist assets in the client. You may get assets airdropped that you really don't care about. Some people see this as spamming.

Now you can burn them, but that costs $WAVES. Also with smart assets, it's possible that you get unburnable tokens just to annoy you.

It would be nice if you could just hide assets you don't really care about in the GUI. You should also have the option to show hidden assets and unhide them. (In case they unexpectedly become worth something.)

### Telegram conversation
![photo_2018-04-26_23-59-03](https://user-images.githubusercontent.com/100821/39334242-30b7ed52-49ae-11e8-8274-8bd06ec259fa.jpg)

**Comment by Jahsus** [comment]
Hello, we just realeased this feature few days ago :) 
Now you can hide unneeded tokens in portfolio and also ypu can switch on the hidden list aswell.
https://prnt.sc/jd7dmw

BTW you can't burn token which are not issued by you, but we are working on that feature too :)
Thank you for your feedback!

**Comment by marsappslab** [comment]
Hello,

What about showing Tokens at  the "Asset" Section showing them by setup or pragmatically ?

**Comment by jasny** [comment]
@marsappslab If you have a new (related) feature request, it's best to open a new ticket.
