### ISSUE TITLE
Autohide pattern for assets to protect against SPAM

### ISSUE THREAD

**Issue by jasny** [wavesplatform/WavesGUI#654]
Wallets are curently overflown with SPAM assets. With #632 we have the power to hide assets. But it's still worth it to create and send these tokens as users will always see them.

SPAM tokens want to convey a message. Typically they want the user to follow a link. Fortunately this makes them easily recognizable.

The wallet to have a property to automatically hide assets. This property would contain a regular expression against the asset name is matched.

The wallet could have a pattern by default hiding the most SPAM tokens and allow the user themselfs to modify this filter. Hiding all tokens with a dot (`/\./`) in the name would be a good start.

![photo_2018-05-21_14-13-16](https://user-images.githubusercontent.com/100821/40307007-24cd350e-5d01-11e8-8759-dc7bde135a00.jpg)

**Comment by travek** [comment]
+1
I want to address (and already addressed) the same issue. 
May be it is reasonable to have a feature in the wallet allowing to send spam tokens on some generic address that will be similar to the token delete from the users assets.

Interesting to see how spam issue got to be actial in the crypto world ))

**Comment by xenohunter** [comment]
Hello, and thanks for the contribution to both of you. Yes, that's a good idea, though we cannot hide all assets following any given pattern without making it possible to restore them. We should figure out an interface where all hidden tokens would be listed.

**Comment by GIvanovWaves** [comment]
Hello, we thought that using autohide pattern is not the best solution in our case.
Legit projects could be hurt if the pattern matched there token.
Spammers could always look up the pattern or reverse engineer it.

We come up another solution -  the publicly maintained community list of Spam tokens, that should help battle spam and it quite effective.
https://github.com/wavesplatform/waves-community
We added an option to disable filtering or you can use another list as you wish.
