### ISSUE TITLE
how to switch from TESTNET Lite Client 0.4.1a to a main network?

### ISSUE THREAD

**Issue by przeor** [wavesplatform/WavesGUI#67]
Hello,

I've cloned the WavesGUI repo, but I see a testnet instead of mainnet.

How to switch to the mainnet?

(I'm on the master branch)

Thanks,
K.

**Comment by beregovoy68** [comment]
Hey,

It's done intentionally. The source code is a development environment so debugging and testing should be done on testnet. If your code is tested and ready for use you can run
`grunt distr`
and you get release packages for testnet and mainnet. Release packages will be properly configured and ready to use.

**Comment by beregovoy68** [comment]
Closing the issue. Reopen it if you'll have some more questions or comments.
