### ISSUE TITLE
How does reissuing coin work on Wave?

### ISSUE THREAD

**Issue by DamaoServices** [wavesplatform/WavesGUI#730]
When I set a custom coin as reissuable. How does that work when I reissue? does every coin holder automatically get more coin based on proportion or it goes to the issuer or I can customize it?

Thanks

**Comment by xenohunter** [comment]
Hello. No, you just get some additional amount of the token on your wallet.

With further questions, please contact [support.wavesplatform.com](https://support.wavesplatform.com/).
