### ISSUE TITLE
How does password check works?

### ISSUE THREAD

**Issue by Ludvaer** [wavesplatform/WavesGUI#838]
I just accidentally entered wrong password in web version and instead of showing "wrong password" message it showed interface, though it looks like it does not work properly so I can't do any meaningful actions or view my orders. I suspect that it managed to make pseudo-successful decryption of seed which, I guess, improbable but not really, counted it as right password, and tried to work with saved correct address and incorrect seed it decrypted. Probably it needs to have additional check if decryprted seed corresponds to saved address.

**Comment by xenohunter** [comment]
Hello! A good remark, thank you! We've added the issue to our backlog.

**Comment by GIvanovWaves** [comment]
The issue is fixed.
