### ISSUE TITLE
Error npm i

### ISSUE THREAD

**Issue by Cristyander** [wavesplatform/WavesGUI#867]
How to solve this problem?

> waves-client@1.0.5 postinstall C:\apps\waves\wavesgui-master
> sh scripts/postinstall.sh

'sh' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.0.5 postinstall: `sh scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CristySamara\AppData\Roaming\npm-cache\_logs\2018-08-26T19_01_31_348Z-debug.log

**Comment by vong-visalsambath** [comment]
I have the same problem when running npm i. :(

` tsc -p ./data-service && ./node_modules/.bin/browserify data-service/index.js -s ds -u ts-utils -u @waves/data-entities -u @waves/signature-generator -u @waves/signature-adapter -u ramda --no-bf -o ./data-service-dist/data-service.js`

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.0.11 data-service: `tsc -p ./data-service && ./node_modules/.bin/browserify data-service/index.js -s ds -u ts-utils -u @waves/data-entities -u @waves/signature-generator -u @waves/signature-adapter -u ramda --no-bf -o ./data-service-dist/data-service.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.0.11 data-service script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lordo\AppData\Roaming\npm-cache\_logs\2018-09-24T08_51_09_311Z-debug.log

**Comment by GIvanovWaves** [comment]
Hello, yeah, there is some problem with scripts on Windows, we working on the fix.
Meanwhile, you can build it with [Git Bash](https://gitforwindows.org/) on Windows with these steps:
`
node_modules/.bin/tsc -p ./data-service && ./node_modules/.bin/browserify data-service/index.js -s ds -u ts-utils -u @waves/data-entities -u @waves/signature-generator -u @waves/signature-adapter -u ramda --no-bf -o ./data-service-dist/data-service.js
`

`
node_modules/.bin/tsc -p ./
`

`
node_modules/.bin/gulp all
`

**Comment by vong-visalsambath** [comment]
@GIvanovWaves Thank so much. It works :)

**Comment by layinka** [comment]
@GIvanovWaves 
I tried your solution on both cygwin and git bash, i get error

```
wavesgui\src\themeConfig\default\icons.less"
The command line is too long.

    at checkExecSyncError (child_process.js:600:11)
    at Object.execSync (child_process.js:637:13)
    at Gulp.<anonymous> (H:\projects\waves\wavesgui\gulpfile.js:243:25)
    at module.exports (H:\projects\waves\wavesgui\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (H:\projects\waves\wavesgui\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (H:\projects\waves\wavesgui\node_modules\orchestrator\index.js:214:10)
    at H:\projects\waves\wavesgui\node_modules\orchestrator\index.js:279:18
    at finish (H:\projects\waves\wavesgui\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (H:\projects\waves\wavesgui\node_modules\orchestrator\lib\runTask.js:60:3)
    at Gulp.Orchestrator._runTask (H:\projects\waves\wavesgui\node_modules\orchestrator\index.js:273:3)
```

**Comment by GIvanovWaves** [comment]
Unfortunately, it's another bug with Windows command line support.
I would recommend using MacOS or Linux for time being.
We are working on a fix.

**Comment by layinka** [comment]
Thanks, that was fixed, but when i try run 

`npm run server`

I get the below, i am not sure how its related with the original issue
```

> npm run build && node server


> waves-client@1.0.21 build H:\WavesGUI
> tsc -p ./ && node_modules/.bin/gulp all

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.0.21 build: `tsc -p ./ && node_modules/.bin/gulp all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.0.21 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Main\AppData\Roaming\npm-cache\_logs\2018-11-06T10_51_47_112Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! waves-client@1.0.21 server: `npm run build && node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the waves-client@1.0.21 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Main\AppData\Roaming\npm-cache\_logs\2018-11-06T10_51_47_166Z-debug.log

```

**Comment by GIvanovWaves** [comment]
Yep, sorry about that, I am reopening this issue, still need additional work on scripts.
Thanks for the feedback.

**Comment by layinka** [comment]
Please is there an  expected date for when this can be fixed?

**Comment by GIvanovWaves** [comment]
Should be fixed for real this time, feel free to reopen if you have any problems.
#1010 #1016 #1022
