### ISSUE TITLE
Asset as a fee while no Waves

### ISSUE THREAD

**Issue by deemru** [wavesplatform/WavesGUI#917]
You can not choice a sponsored asset as a fee when you do not have Waves:

![image](https://user-images.githubusercontent.com/10706633/46350459-832fb480-c65d-11e8-878a-f226d1e1a4f9.png)

But if you click to Mass Transfer and back the error disappears.

![image](https://user-images.githubusercontent.com/10706633/46350515-a0648300-c65d-11e8-9640-264dbdac3193.png)

**Comment by GIvanovWaves** [comment]
Hi, this should be fixed at this point, closing this issue.
