### ISSUE TITLE
Cann't log in by seed in waveswallet.io

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#935]
Empty balance.
Also some tokens not available on DEX  by their ASSET ID - from old waves-lite-client.

**Comment by xenohunter** [comment]
Sorry, we don't support that domain anymore. Please, use [client.wavesplatform.com](https://client.wavesplatform.com/).

**Comment by xenohunter** [comment]
@tsigel, please, close the issue.

**Comment by username1565** [comment]
Hey, there is working waves-lite-client-mainnet-0.5.22.js but nulled balances.
I using waves-lite-client 0.5.18 from zip archive, and this working for me.
And I do not really trust other sites.

If you can fix this, please do this.
If you lost the contol of this domain, maybe private keys and seeds can be stoled?!!

**Comment by xenohunter** [comment]
Sorry, I'm not working for Waves anymore, hope the team will answer your question.

**Comment by username1565** [comment]
Oww...
I see the main differences in the url of XHR queries:
```https://nodes.wavesnodes.org/blocks/height``` - not opening for me and return SSL error.
```https://nodes.wavesnodes.com/blocks/height``` - opening good.

So, I can fix this myself, to locally working, by just changing this:
```
121808:            NODE_ADDRESS: 'https://nodes.wavesnodes.org',
121809:            COINOMAT_ADDRESS: 'https://coinomat.com',
121810:            MATCHER_ADDRESS: 'https://matcher.wavesnodes.org',
121811:            DATAFEED_ADDRESS: 'https://marketdata.wavesnodes.org'
```
to this:
```
121808:            NODE_ADDRESS: 'https://nodes.wavesnodes.com',
121809:            COINOMAT_ADDRESS: 'https://coinomat.com',
121810:            MATCHER_ADDRESS: 'https://matcher.wavesnodes.com',
121811:            DATAFEED_ADDRESS: 'https://marketdata.wavesnodes.com'
```
and maybe you can do this on that host.

Best regards. Issue is closed.

**Comment by username1565** [comment]
P.S. Also, I see one more console.log error:
```
XMLHttpRequest cannot load https://nodes.wavesnodes.com/transactions/info/2sBjKeKCgTBYTpGARMKosU1uYJWct68RSZFHKvMzPieU. The 'Access-Control-Allow-Origin' header has a value 'http://wavesexplorer.com' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access. 
```
You can disable header for the response of this query.
2sBjKeKCgTBYTpGARMKosU1uYJWct68RSZFHKvMzPieU - this is asset ID of airdropped token.
