### ISSUE TITLE
Blockchain optimization

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#979]
Hello, again.
I see, on the site http://wavesexplorer.com/
now waves-blockchain contains over 1,200,000 blocks.
Maybe need long time to syncrhonize this all on full node.

Can you add in the future the optimization functions for blockchain height?
How I see this?
1. Old long blockhain is archived to zip-archive.
2. Calculating the hash from archive.
3. Including the hash of archive - to the first genesis block of new blockchain.
4. Generating few blocks with all tokens to all users.
5. Continue LPOS mining from last block of optimized blockchain.

In this case the syncronization between the nodes will be faster,
and old transactions will be excluded from the optimized blockchain.
And each node can verify new blockchain.
Also, in the first block can be included the magnet link with hash,
to download old blockchain, parse this, and see old transaction history.

Maybe fast synchronization can be realized, using checkpoints,
but full blockchain need to save for each node. And what about long time?
For example, Ethereum have blockchain height over 6,000,000 blocks!!!

Best regards.

**Comment by KardanovIR** [comment]
Hello, @username1565

This repository is for Waves Client, not Waves Node. You can open a new issue for appropriate repository here https://github.com/wavesplatform/Waves

**Comment by username1565** [comment]
Ok. Opened: https://github.com/wavesplatform/Waves/issues/1642
This is closed.
