### ISSUE TITLE
client.wavesplatform.com

### ISSUE THREAD

**Issue by username1565** [wavesplatform/WavesGUI#981]
Hello. Can you add on your new web-wallet
on the DEX
the option to exchange
**any token to any token**, by using asset ID's
like in old DEX, from web-wallet waves-lite-client 0.x.x?

For example, I want to exchange
```WavesGo (ASSET ID: 4eT6R8R2XuTcBuTHiXVQsh2dN2mg3c2Qnp95EWBNHygg)```
to
```Wavesnode.NET (ASSET ID: AxAmJaro7BJ4KasYiZhw7HkjwgYtt2nekPuF2CN9LMym)```.
How to do this, using https://client.wavesplatform.com/ ??

This exchange way is working in waves-lite-client 0.5.18.zip,
by copy and paste asset ID's in the fields on DEX...

____________________________________________________________________________________________________
Also, I have one more proposition...
I see the Waves was been added to the https://www.bestchange.ru/
as one of the ticker for exchange.
But as you can see, many exchagnes not supporting many ways to exchange.

That could be fixed, if you ask them all to add WAVES.
This requires an interface for automated trading and transaction verification.
I do not think that this is a problem for you all,
because I saw the Waves on the coin exchanges.
This has significantly expanded the trading market
by all disabled ways for exchange Waves.

Best regards.

**Comment by tsigel** [comment]
Hello!
For WavesGo/Wavesnode.NET exchanging u should just add both assets (with "/") in search.
For example "WavesGo/Wavesnode" for search by name or "4eT6R8R2XuTcBuTHiXVQsh2dN2mg3c2Qnp95EWBNHygg/AxAmJaro7BJ4KasYiZhw7HkjwgYtt2nekPuF2CN9LMym" for search by id.

**Comment by username1565** [comment]
I leave this issue opened until the title tooltip has been added,
because the information contained here may be useful to many users.

**Comment by GIvanovWaves** [comment]
Hi, we will discuss this issue with our team, thanks for the feedback.

**Comment by username1565** [comment]
Look at this button: http://jsfiddle.net/39yfgnhk/
There is using CSS3, HTML and pureJS.
You can using this to switch limit and market position.
I did this in waveswallet waves-lite-client 0.5.18.zip on client-side filling buy and sell order form...

Have a nice day.

**Comment by username1565** [comment]
Can I see random asset distribution (rich list), like this http://dev.pywaves.org/assets/cc
or this: http://dev.pywaves.org/assets/mgo
or this: http://dev.pywaves.org/assets/zrc
Here is available list of all holders and balances.
But if I want to see holders of this token:
http://dev.pywaves.org/assets/6AnChL44kugXpJKEf2AKvYPumvmEjqjKSTiAHfvtu9C4
I cann't do this. What to do if I want to make airdrop waves comissions to them all?
Is there any service to see richlist for random token?

**Comment by username1565** [comment]
The button and info about exchanges on bestchange.ru
repeated [here](https://github.com/wavesplatform/WavesGUI/issues/1067).

I see title tooltip.
This issue is closed.
