### ISSUE TITLE
Since Date.now() returns Milliseconds anyway, we shouldn't convert it to milliseconds after if this is used  

### ISSUE THREAD

**Issue by BlockchainJames** [wavesplatform/WavesGUI#998]
https://github.com/wavesplatform/WavesGUI/blob/d7314cba1876df88e2fe5fd7bf57f8f8cba65721/src/modules/dex/services/CandlesService.js#L41

https://github.com/wavesplatform/WavesGUI/blob/d7314cba1876df88e2fe5fd7bf57f8f8cba65721/src/modules/dex/services/CandlesService.js#L43

Maybe?

Im using a custom candles service, and the dateTo is being passed through to the API multiplied by 1000

**Comment by tsigel** [comment]
Thanks for your PR!
We will fix it in next release!

**Comment by GIvanovWaves** [comment]
Fixed at 839b395
#1012
